#!/usr/bin/env perl
use App::Cope;

my @headers = qw[Device Boot Start End Blocks Id System];

sub process {
  if (/^\s*Device/) {
    for my $h (@headers) { mark $h => 'underline'; }
  }
  else {
    # device and size
    line qr{^(Disk )(\S+?)(: )(\S+ GB)} => map { ( "underline", "underline $_" ) } 'yellow bold', 'green bold';

    # label type
    line qr{(Disk label type:) (dos)?(gpt)?} => 'bold', 'red bold', 'magenta bold';

    # paritions
    line qr{(?:^|:)(\S\S+/)(\S\S+)(?:\s+(\*))?} => 'blue', 'blue bold', 'green bold';
  }
}

run( \&process, real_path, @ARGV );
