#!/usr/bin/env perl
use App::Cope;
use Regexp::Common qw[net];

# these colours have only been tested with 'ip a'

sub process {
  # interface number
  line qr{^(\d+): }              => 'bold';

  # interface name
  line qr{^\d+: +(.+?):}          => 'yellow';

  # link type
  line qr{link/(.+?) }           => 'bold';

  # aliases
  line qr{scope .* (\w+)$}       => 'yellow';
  line qr{scope .* (\w+):\w+$}   => 'yellow';
  line qr{scope .* \w+:(\w+)$}   => 'yellow bold';

  # mac address
  line qr{link/.+? ([0-9A-F-:]+) brd [0-9A-F-:]+}i => 'red bold';

  # ip address
  line qr{inet ($RE{net}{IPv4})} => 'green ';

  # subnet
  line qr{/(\d+) brd}            => 'green bold';

  # netmask
  line qr{inet $RE{net}{IPv4}/\d+ brd ($RE{net}{IPv4})} => 'cyan';

  # ipv6 address
  line qr{inet6 ([0-9A-F-:]+)}i  => 'blue';

  # ipv6 subnet
  line qr{/(\d+) scope}          => 'blue bold';

}

run( \&process, real_path, @ARGV );
