#!/usr/bin/env perl
use App::Cope;
$App::Cope::line_buffered = 0;

sub process {
        # Hit http://apt.puppetlabs.com wheezy/main amd64 Packages
        # Ign http://security.debian.org testing/updates/contrib Translation-en
        # Get: 1 http://http.debian.net experimental Release [161 kB]

        line qr{^(Ign)} => 'yellow';
        line qr{^(Hit)} => 'green';
        line qr{(Get): (\d+)(.*) \[(.*)\]} => 'cyan', 'bold', '', 'blue';
        line qr{\d(T)\s} => 'red bold';

        # Fetched 7,819 B in 8s (910 B/s)
        line qr{^Fetched ([\d,]+)} => 'blue';
        line qr{in (\d+)s \((.*)\)} => 'yellow', 'blue';

        # The following packages will be upgraded:
        line qr{The following will be (upgraded):} => 'magenta';

        # The following packages will be REMOVED:
        line qr{The following packages will be (REMOVED):} => 'red bold';

        # The following NEW packages will be installed:
        line qr{The following (NEW) packages will be (installed):} => 'green bold', 'green';

        # 1 packages upgraded, 0 newly installed, 0 to remove and 686 not upgraded.
        line qr{(\d+) packages upgraded} => 'magenta';
        line qr{(\d+) newly installed}   => 'green';
        line qr{(\d+) to remove}         => 'red';
        line qr{and (\d+) not upgraded}  => 'cyan';

        # Do you want to continue? [Y/n/?]
        line qr{\[([Yy])/([Nn])/(\?)\]}        => 'green', 'red', 'yellow';

        # (Reading database ... 213736 files and directories currently installed.)
        line qr{(\d+) files and directories}   => 'bold';

        # Current status: 686 updates [-1].
        line qr{Current status: (\d+) updates} => 'bold';

        # Setting up smplayer (0.8.4-1) ...
        line qr{(Setting up) ([\w|-]+) \((.*)\) ...}   => 'green', 'blue bold', 'blue';

        # Preparing to replace smplayer 0.8.3-1 (using .../smplayer_0.8.4-1_amd64.deb) ...
        line qr{Preparing to replace ([\w|-]+) \((.*)\) \(using (.*)\) ...} => ' blue bold', 'blue', 'bold';

        # Unpacking replacement smplayer ...
        # Unpacking smplayer (from .../smplayer_0.8.4-1_amd64.deb) ...
        line qr{Unpacking ([\w|-]+)} => 'blue bold'; # ([\w|-|^replacement]+)} Maybe? matches replacemenet now too...
        line qr{Unpacking replacement ([\w|-]+)} => 'blue bold';

        # Removing smplayer-themes ...
        # Removing smplayer ...
        # TODO fix so it doesn't match: Removing all DKMS Modules
        line qr{(Removing) ([\w|-]+) ...} => 'red bold', 'blue bold';

        # 63% [6 emacs-snapshot-common 8,885 kB/20.5 MB 43%]
        line qr{(^\d+)\% \[(\d+) ([\w|-]+) (.*) (\d+)\%\]} => 'green bold', 'bold', 'blue bold', 'blue', 'green';

}

run( \&process, real_path, @ARGV );
