#!/usr/bin/env perl
use App::Cope;
$App::Cope::line_buffered = 0;

sub process {
        # Hit http://apt.puppetlabs.com wheezy/main amd64 Packages
        # Ign http://security.debian.org testing/updates/contrib Translation-en
        # Get: 1 http://http.debian.net experimental Release [161 kB]

        line qr{^(Ign)} => 'yellow';
        line qr{^(Hit)} => 'green';
        line qr{(Get): (\d+)(.*) \[(.*)\]} => 'cyan', 'bold', '', 'blue';
        line qr{\d(T)\s} => 'red bold';

        # Fetched 7,819 B in 8s (910 B/s)
        line qr{^Fetched ([\d,]+)} => 'blue';
        line qr{in (\d+)s \((.*)\)} => 'yellow', 'blue';

        # The following packages will be upgraded:
        line qr{The following will be (upgraded):} => 'magenta';

        # The following packages will be REMOVED:
        line qr{The following packages will be (REMOVED):} => 'red bold';

        # The following NEW packages will be installed:
        line qr{The following (NEW) packages will be (installed):} => 'green bold', 'green';

        # 1 packages upgraded, 0 newly installed, 0 to remove and 686 not upgraded.
        line qr{(\d+) packages upgraded} => 'magenta';
        line qr{(\d+) newly installed}   => 'green';
        line qr{(\d+) to remove}         => 'red';
        line qr{and (\d+) not upgraded}  => 'cyan';

        # Do you want to continue? [Y/n/?]
        # Accept this solution? [Y/n/q/?]
        line qr{\[([Yy])/([Nn])/(\?)\]}        => 'green', 'red', 'yellow';
        line qr{\[([Yy])/([Nn])/([Qq])/(\?)\]}        => 'green', 'red', 'magenta', 'yellow';

        # (Reading database ... 213736 files and directories currently installed.)
        line qr{(\d+) files and directories}   => 'bold';

        # Current status: 686 updates [-1].
        line qr{Current status: (\d+) updates} => 'bold';

        # Setting up smplayer (0.8.4-1) ...
        # Setting up libqt4-declarative:amd64 (4:4.8.2+dfsg-11) ...
        line qr{(Setting up) ([\w|-|:]+) \((.*)\) ...}   => 'green', 'blue bold', 'blue';

        # Preparing to replace smplayer 0.8.3-1 (using .../smplayer_0.8.4-1_amd64.deb) ...
        line qr{Preparing to replace ([\w|-]+) \((.*)\) \(using (.*)\) ...} => ' blue bold', 'blue', 'bold';

        # Unpacking replacement smplayer ...
        # Unpacking smplayer (from .../smplayer_0.8.4-1_amd64.deb) ...
        line qr{Unpacking ([\w|-]+)} => 'blue bold'; # ([\w|-|^replacement]+)} Maybe? matches replacemenet now too...
        line qr{Unpacking replacement ([\w|-]+)} => 'blue bold';

        # Removing smplayer-themes ...
        # Removing smplayer ...
        # TODO fix so it doesn't match: Removing all DKMS Modules
        line qr{(Removing) ([\w|-]+) ...} => 'red bold', 'blue bold';

        # 63% [6 emacs-snapshot-common 8,885 kB/20.5 MB 43%]
        line qr{(^\d+)\% \[(\d+) ([\w|-]+) (.*) (\d+)\%\]} => 'green bold', 'bold', 'blue bold', 'blue', 'green';

        ## aptitude show
        # Package: zsh-beta
        line qr{^(Package): ([\w|-|:]+)} => 'bold', 'blue bold';

        # State: not installed
        # State: installed
        line qr{^(State): (not installed)} => 'bold', 'red';
        line qr{^(State): (installed)} => 'bold', 'green';

        # Automatically installed: no
        line qr{^(Automatically installed): (no)} => 'bold', 'red';
        line qr{^(Automatically installed): (yes)} => 'bold', 'green';

        # Version: 1.0.1-1
        line qr{^(Version): (.*)} => 'bold', 'blue';

        # Homepage: http://htop.sourceforge.net
        line qr{^(Homepage):} => 'bold';

        # Architecture: amd64
        line qr{^(Architecture):} => 'bold';

        # Section: utils
        line qr{^(Section):} => 'bold';

        # Conflicts: htop
        line qr{^(Conflicts):} => 'bold';

        # Suggests: strace, ltrace
        line qr{^(Suggests):} => 'bold';

        # Description: interactive processes viewer
        line qr{^(Description):} => 'bold';

        # Depends: libc6 (>= 2.3.4), libncursesw5 (>= 5.6+20070908), libtinfo5
        line qr{^(Depends):} => 'bold';

        # Maintainer: Eugene V. Lyubimkin <jackyf@debian.org>
        line qr{^(Maintainer):} => 'bold';

        # Uncompressed Size: 216 k
        line qr{^(Uncompressed Size):} => 'bold';

        # Priority: optional
        line qr{^(Priority):} => 'bold';

        # The following packages have unmet dependencies:
        #  skype:i386 : Depends: libasound2:i386 (>= 1.0.16) but it is not going to be installed.
        #               Depends: libc6:i386 (>= 2.3.6-6~) but it is not going to be installed.
        line qr{^ ([\w|-|:]+) : Depends: ([\w|-|:]+) \((.*)\)} => 'blue bold', 'blue bold', 'blue';
        line qr{^\s+Depends: ([\w|-|:]+) \((.*)\)} => 'blue bold', 'blue';

        # but it is not going to be installed
        line qr{but it is (not) going to be installed} => 'red bold';

        # Remove the following packages:
        # 1)     skype:i386
        line qr{^(Remove the following packages:)} => 'red bold';
        line qr{^(\d+)\)\s+([\w|-|:]+)} => 'bold', 'blue bold';

        # Package htop:
        # Package htop:i386:
        line qr{^(Package) ([\w|-|:]+):} => 'bold', 'blue bold';

        # i   1.0.1-1    testing     990
        # p   1.0.2-1    experimental      1
        line qr{^(i)\s+} => 'green bold';
        line qr{^(p)\s+} => 'red';
        line qr{^(v)\s+} => 'magenta';
        line qr{^(c)\s+} => 'yellow';
        line qr{^(d)\s+} => 'red';
        line qr{^\w\s(A)\s+} => 'green';
        line qr{^\w\s+([\d|.\\|-]+)\s+([\w|-|:]+)\s+(\d+)} => 'blue bold', 'yellow', 'red';
}

run( \&process, real_path, @ARGV );


# Need to get 0 B/45.8 MB of archives. After unpacking 267 MB will be used.
